BlogSite/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import home,search

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor',include('ckeditor_uploader.urls')),
    path('',home,name='home'),
    path('user/',include('userInfo.urls')),
    path('blog/',include('blog.urls')),
    path('comment/',include('comment.urls')),
    path('search/',search,name='search'),
]

urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from . import views

urlpatterns=[
    path('<username>',views.blog_list,name='blog_list'),
    path('articles/<int:blog_pk>',views.blog_detail,name='blog_detail'),
    path('type/<int:blog_type_pk>',views.blogs_with_type,name='blogs_with_type'),
    path('manage/',views.blog_manage,name='blog_manage'),
    path('add/',views.blog_add,name='blog_add'),
    path('change/<int:blog_pk>',views.blog_change,name='blog_change'),
    path('delete/<int:blog_pk>',views.blog_delete,name='blog_delete'),
    path('blog_type/manage/',views.blog_type_manage,name='blog_type_manage'),
    path('blog_type/add/',views.blog_type_add,name='blog_type_add'),
    path('blog_type/change/<int:blog_type_pk>',views.blog_type_change,name='blog_type_change'),
    path('blog_type/delete/<int:blog_type_pk>',views.blog_type_delete,name='blog_type_delete'),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
# from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField

# Create your models here.
class BlogType(models.Model):
    type_name=models.CharField(max_length=20,verbose_name='博客类型')
    author=models.ForeignKey(User,on_delete=models.DO_NOTHING,verbose_name='作者')
    def __str__(self):
        return self.type_name
        
    class Meta:
        verbose_name='博客类型'
        verbose_name_plural=verbose_name
        
class Blog(models.Model):
    title=models.CharField(max_length=50,verbose_name='标题')
    blog_type=models.ForeignKey(BlogType,on_delete=models.DO_NOTHING,verbose_name='博客类型')
    # content=models.TextField(verbose_name='博客内容')
    # content=RichTextField()
    content=RichTextUploadingField()
    author=models.ForeignKey(User,on_delete=models.DO_NOTHING,verbose_name='作者')   
    created_time=models.DateTimeField(auto_now_add=True,verbose_name='创作时间')
    last_update_time=models.DateTimeField(auto_now=True,verbose_name='上次修改时间')
    def readnum_function(self):
        try:
            return self.readnum.read_num
        except Exception as e:
            return 0
    readnum_function.short_description='阅读量'
    def __str__(self):
        return self.title
        
    class Meta:
        ordering=['-created_time']
        verbose_name='博客'
        verbose_name_plural=verbose_name
        
class ReadNum(models.Model):
    read_num=models.IntegerField(default=0,verbose_name='阅读量')
    blog=models.OneToOneField(Blog,on_delete=models.CASCADE,verbose_name='博客')
    
    class Meta:
        verbose_name='阅读量'
        verbose_name_plural=verbose_name

comment/forms.py
from django import forms

class CommentForm(forms.Form):
    object_blog=forms.CharField(widget=forms.HiddenInput)
    object_id=forms.IntegerField(widget=forms.HiddenInput)
    text=forms.CharField(label='欢迎评论',widget=forms.Textarea(attrs={'class':"form-control",'placeholder':'请在此处评论','rows':5}))
    
    reply_comment_id=forms.IntegerField(widget=forms.HiddenInput(attrs={'id':'reply_comment_id'}))

blog/views.py
from django.shortcuts import render,get_object_or_404,redirect,reverse
from .models import Blog,BlogType,ReadNum
from django.contrib.auth.models import User
from django.core.paginator import Paginator
from comment.models import Comment
from comment.forms import CommentForm

# Create your views here.
def blog_list(request,username):
    page_num=request.GET.get('page',1)#获取页面参数(request.GET是字典)，page_num是字符串
    user=User.objects.get(username=username)
    blogs_all_list=Blog.objects.filter(author=user)
    paginator=Paginator(blogs_all_list,5)#每5个进行分页
    page_of_blogs=paginator.get_page(page_num)
    
    blog_types=BlogType.objects.filter(author=user)
    my_blog_types=[]
    for blog_type in blog_types:# 添加每种类型对应的博客数量，利用python可以临时添加实例变量和类变量的属性
        blog_type.blog_count = Blog.objects.filter(blog_type=blog_type).count()
        my_blog_types.append(blog_type)
    
    context={}
    context['page_of_blogs']=page_of_blogs
    context['blog_types']=my_blog_types
    context['author']=username
    return render(request,'blog_list.html',context)
    
def blog_detail(request,blog_pk):
    context={}
    blog=get_object_or_404(Blog,pk=blog_pk)
    #阅读量加一
    if not request.COOKIES.get('blog_%s_read'%blog_pk):#字典
        if ReadNum.objects.filter(blog=blog).count():
            #存在记录
            readnum=ReadNum.objects.get(blog=blog)
            readnum.read_num+=1
            readnum.save()
        else:
            #不存在记录
            readnum=ReadNum()
            readnum.read_num=1
            readnum.blog=blog
            readnum.save()
    #获取评论
    comments=Comment.objects.filter(comment_blog=blog,parent=None)
    
    context['previous_blog']=Blog.objects.filter(created_time__gt=blog.created_time).last()
    context['next_blog']=Blog.objects.filter(created_time__lt=blog.created_time).first()
    context['blog']=blog
    context['comments']=comments
    context['comment_form']=CommentForm(initial={'object_blog':blog.title,'object_id':blog_pk,'reply_comment_id':0})#设置表单value
    response=render(request,'blog_detail.html',context)
    response.set_cookie('blog_%s_read'%blog_pk,'true',max_age=600)
    return response
    
def blogs_with_type(request,blog_type_pk):#参数变量名必须与urls中的相同
    page_num=request.GET.get('page',1)#获取页面参数(request.GET是字典)
    blog_type=get_object_or_404(BlogType,pk=blog_type_pk)# 是个对象
    blogs_all_list=Blog.objects.filter(blog_type=blog_type)
    paginator=Paginator(blogs_all_list,5)#每3页进行分页
    page_of_blogs=paginator.get_page(page_num)#django特有的,错误就第一页/实际是最后一页
    
    blog_types=BlogType.objects.filter(author=blog_type.author)
    my_blog_types=[]
    for per_blog_type in blog_types:# 添加每种类型对应的博客数量，利用python可以临时添加实例变量和类变量的属性
        per_blog_type.blog_count = Blog.objects.filter(blog_type=per_blog_type).count()
        my_blog_types.append(per_blog_type)
    
    context={}
    #blog_type=get_object_or_404(BlogType,pk=blog_type_pk)# 是个对象
    #context['blogs']=Blog.objects.filter(blog_type=blog_type)
    context['page_of_blogs']=page_of_blogs# 加的
    context['blog_type']=blog_type
    context['blog_types']=my_blog_types
    return render(request,'blogs_with_type.html',context)

# 博客管理    
def blog_manage(request):
    user=User.objects.get(username=request.user.username)
    my_blogs=Blog.objects.filter(author=user)
    
    context={}
    context['my_blogs']=my_blogs
    context['count']=my_blogs.count()
    return render(request,'blog_manage.html',context)
    
def blog_add(request):# 增加博客
    if request.method=='POST':
        title=request.POST.get('title','')
        blog_type_pk=int(request.POST.get('blog_type',''))
        blog_type=get_object_or_404(BlogType,pk=blog_type_pk)
        content=request.POST.get('content','')
        user=User.objects.get(username=request.user.username)
        b=Blog(title=title,blog_type=blog_type,content=content,author=user)# 开始增加博客
        b.save()
        return redirect(reverse('blog_manage'))
    user=User.objects.get(username=request.user.username)  
    context={}
    context['blog_types']=BlogType.objects.filter(author=user)
    return render(request,'blog_add.html',context)
    
def blog_change(request,blog_pk):# 修改博客
    if request.method=='POST':
        title=request.POST.get('title','')
        blog_type_pk=int(request.POST.get('blog_type',''))
        blog_type=get_object_or_404(BlogType,pk=blog_type_pk)
        content=request.POST.get('content','')
        b=get_object_or_404(Blog,pk=blog_pk)# 获取博客
        if b.author.username==request.user.username:# 验证是否是本作者要修改博客
            b.title=title # 开始修改博客
            b.blog_type=blog_type
            b.content=content
            b.save()
            return redirect(reverse('blog_manage'))
    user=User.objects.get(username=request.user.username)
    blog=get_object_or_404(Blog,pk=blog_pk)
    if user.username==blog.author.username:# 验证是否是本人要修改博客
        context={}
        context['blog']=blog
        context['blog_types']=BlogType.objects.filter(author=user)
        return render(request,'blog_change.html',context)
    
def blog_delete(request,blog_pk):# 删除博客
    blog=get_object_or_404(Blog,pk=blog_pk)
    if blog.author.username==request.user.username:# 验证是否是本作者要删除博客
        blog.delete()
    return redirect(reverse('blog_manage'))

# 博客类型管理    
def blog_type_manage(request):
    user=User.objects.get(username=request.user.username)
    blog_types=BlogType.objects.filter(author=user)
    my_blog_types=[]
    for blog_type in blog_types:# 添加每种类型对应的博客数量，利用python可以临时添加实例变量和类变量的属性
        blog_type.blog_count = Blog.objects.filter(blog_type=blog_type).count()
        my_blog_types.append(blog_type)
    context={}
    context['my_blog_types']=my_blog_types
    context['count']=blog_types.count()
    return render(request,'blog_type_manage.html',context)
    
def blog_type_add(request):# 增加博客类型
    if request.method=='POST':
        blog_type=request.POST.get('blog_type','')
        user=User.objects.get(username=request.user.username)
        bt=BlogType(type_name=blog_type,author=user)# 开始增加博客
        bt.save()
        return redirect(reverse('blog_type_manage'))  
    context={}
    return render(request,'blog_type_add.html',context)
    
def blog_type_change(request,blog_type_pk):# 修改博客类型
    if request.method=='POST':
        blog_type=request.POST.get('blog_type','')
        bt=get_object_or_404(BlogType,pk=blog_type_pk)# 获取博客类型
        if bt.author.username==request.user.username:# 验证是否是本作者要修改博客类型
            bt.type_name=blog_type
            bt.save()
            return redirect(reverse('blog_type_manage'))
    blog_type=get_object_or_404(BlogType,pk=blog_type_pk)
    if blog_type.author.username==request.user.username:# 验证是否是本作者要修改博客类型
        context={}
        context['blog_type']=blog_type
        return render(request,'blog_type_change.html',context)
        
def blog_type_delete(request,blog_type_pk):# 删除博客类型
    blog_type=get_object_or_404(BlogType,pk=blog_type_pk)
    if blog_type.author.username==request.user.username:# 验证是否是本作者要删除博客类型
        blog_type.delete()
    return redirect(reverse('blog_type_manage'))

blog/templates/blog_add.html
{% extends 'base.html' %}

{# 页面标题 #}
{% block title %}
增加博客
{% endblock %}

{# 页面内容 #}
{% block content %}
<div class="container">
	<div class="row">
		<div class="col-xs-10 col-sm-8 col-xs-offset-1 col-sm-offset-2">
			<form action="" method="POST">
				{% csrf_token %}
				<div class="input-group">
					<label for="id_title">博客标题</label>
					<input type="text" name="title" required placeholder="请输入博客标题" maxlength="30" id="id_title" class="form-control" />
				</div><br>
				<div class="input-group">
					<label for="id_blog_type">博客类型</label>
					<select class="form-control" name="blog_type" id="id_blog_type" required>
						{% for blog_type in blog_types %}
						<option value ="{{blog_type.id}}">{{blog_type.type_name}}</option>
						{% empty %}
						{% endfor %}
					</select>
					<a href="{% url 'blog_type_add' %}" class="pull-right"><span class="glyphicon glyphicon-plus" aria-hidden="true">增加</span></a>
				</div><br>
				<div>
					<label for="id_content">博客内容</label>
					<div class="form-group">
						<textarea id="id_content" name="content" class="form-control" rows="12" required placeholder="请在此处写博客内容"></textarea>
					</div>
				</div>
				<br>
				<input type="submit" value="保存" class="btn btn-primary pull-right">
			</form>
		</div>
	</div>
</div>
{% endblock %}

blog/templates/blog_change.html
{% extends 'base.html' %}

{# 页面标题 #}
{% block title %}
修改博客
{% endblock %}

{# 页面内容 #}
{% block content %}
<div class="container">
	<div class="row">
		<div class="col-xs-10 col-sm-8 col-xs-offset-1 col-sm-offset-2">
			<form action="" method="POST">
				{% csrf_token %}
				<div class="input-group">
					<label for="id_title">博客标题</label>
					<input type="text" name="title" required placeholder="请输入博客标题" maxlength="30" id="id_title" class="form-control" value="{{blog.title}}" />
				</div><br>
				<div class="input-group">
					<label for="id_blog_type">博客类型</label>
					<select class="form-control" name="blog_type" id="id_blog_type" required>
						{% for blog_type in blog_types %}
							{% if blog.blog_type.id is blog_type.id %}
								<option value ="{{blog_type.id}}" selected="selected">{{blog_type.type_name}}</option>
							{% else %}
								<option value ="{{blog_type.id}}">{{blog_type.type_name}}</option>
							{% endif %}
						{% empty %}
						{% endfor %}
					</select>
					<a href="{% url 'blog_type_add' %}" class="pull-right"><span class="glyphicon glyphicon-plus" aria-hidden="true">增加</span></a>
				</div><br>
				<div>
					<label for="id_content">博客内容</label>
					<div class="form-group">
						<textarea id="id_content" name="content" class="form-control" rows="12" required placeholder="请在此处写博客内容">{{blog.content}}</textarea>
					</div>
				</div>
				<br><a href="{% url 'blog_delete' blog.id %}" class="btn btn-danger pull-left">删除</a>
				<input type="submit" name="save" value="保存" class="btn btn-primary pull-right">
			</form>
		</div>
	</div>
</div>
{% endblock %}

blog/templates/blog_detail.html
{% extends 'base.html' %}

{# 页面标题 #}
{% block title %}
{{blog.title}}
{% endblock %}

{# 页面内容 #}
{% block content %}
	<link rel="stylesheet" href="/static/blog/blog_list.css">
	<div class="container">
		<div class="row">
			<div class="col-xs-10 col-xs-offset-1">
				<h3>{{blog.title}}</h3>
				<ul class="blog-info-discription">
					<li>作者：<a href="{% url 'blog_list' blog.author %}">{{blog.author}}</a></li>
					<li>分类：<a href="/blog/type/{{blog.blog_type.pk}}">{{blog.blog_type}}</a></li>
					<!--p>发表日期：{{blog.created_time|date:"Y-m-d G:n:s"}}</p-->
					<li>发表日期：{{blog.created_time}}</li>
					<li>最近修改日期：{{blog.last_update_time}}</li>
					<li>阅读({{blog.readnum_function}})</li>
				</ul>
				<div class="blog-content">{{blog.content|safe}}</div>
				<div class="blog-more">
					<p>上一篇：
					{% if previous_blog %}
						<a href="/blog/articles/{{previous_blog.pk}}">{{previous_blog.title}}</a>
					{% else %}
						没有了
					{% endif %}
					</p>
					<p>下一篇：
					{% if next_blog %}
						<a href="/blog/articles/{{next_blog.pk}}">{{next_blog.title}}</a>
					{% else %}
						没有了
					{% endif %}
					</p>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-xs-10 col-xs-offset-1">
				<div class="comment-area">
				<h3 class="comment-area-title">提交评论</h3>
				{% if user.is_authenticated %}
					<form action="/comment/update_comment" method="POST" style="overflow:hidden" id="reply_comment">
						{% csrf_token %}
						<label for="comment_text">{{user.username}}，</label>
						<div id="reply_content_container">
							<p id="appear" style="color:red"></p>
							<div id="reply_content"></div>
						</div>
						{{comment_form}}
						<!--div class="form-group">
							<label for="comment_text">{{user.username}}，欢迎评论~</label>
							<textarea id="comment_text" class="form-control" name="text" rows="6"></textarea>
						</div>
						<input type="hidden" name="object_id" value="{{blog.pk}}">
						<input type="hidden" name="object_blog" value="{{blog.title}}"-->
						<input type="submit" class="btn btn-primary" value="评论" style="float:right">
					</form>
				{% else %}
					未登录，登录之后方可评论~~~
					<a class="btn btn-primary" href="{% url 'login' %}">登录</a>
					<span>或者</span>
					<a class="btn btn-danger" href="{% url 'register' %}">注册</a>
				{% endif %}
				</div>
				<hr>
				<div class="comment-area">
					<h3 class="comment-area-title">评论列表区域（<a href="javascript:reply(0);">评论博客</a>）</h3>
				  <div id="comment_list">
					{% for comment in comments %}
					<div class="comment">
						<strong>{{comment.user}}</strong>({{comment.comment_time}})：
						<div id="comment_{{comment.pk}}">
							{{comment.text}}
						</div>
						<a href="javascript:reply({{ comment.pk }});">回复</a>
						{% for reply in comment.root_comment.all %}
						<div class="reply">
							<strong>{{reply.user}}</strong>({{reply.comment_time}})
							<span style="color:red">回复</span>
							<strong>{{reply.parent.user}}</strong>：
							<div id="comment_{{reply.pk}}">
								{{reply.text}}
							</div>
							<a href="javascript:reply({{ reply.pk }});">回复</a>
						</div>
						{% endfor %}
					</div>
					
					{% empty %}
					<p>欢迎来评论哦</p>
					{% endfor %}
				  </div>
				</div>
			</div>
		</div>
	</div>
	<br>
	<script>
	function reply(reply_comment_id){
		$("#reply_comment_id").val(reply_comment_id);
		var html=$("#comment_"+reply_comment_id).html();
		$("#reply_content").html(html);
		$("#reply_content_container").show();
		$('html').animate({scrollTop:$("#reply_comment").offset().top-60},300);
		appear(reply_comment_id);
	}
	function appear(reply_comment_id){
		if(reply_comment_id==0){
			document.getElementById("appear").innerHTML="";
			document.getElementById("reply_content").innerHTML="";
		}else{
			document.getElementById("appear").innerHTML="回复";
		}
	}
	</script>
{% endblock %}
{% block script_extends %}
	<script>
		$("#reply_comment").submit(function(){
			//异步提交
			$.ajax({
				url:"/comment/update_comment",
				type:"POST",
				data:$(this).serialize(),
				cache:false,
				success:function(data){
					console.log(data);
					if(data['status']=="SUCCESS"){
						if($("#reply_comment_id").val()=='0'){
							//插入评论
							var comment_html='<div class="comment">'+'<strong>'+data['username']+'</strong>'+'(刚刚)'+'：'
							+'<div>'+data['text']+'<div>'+'<a href="javascript:reply('+data['pk']+');">回复</a>'+'</div>';
							$('#comment_list').prepend(comment_html);
							//清空编辑框的内容
							$('#id_text').val('');
						}else{
							//插入回复
							var comment_html='<div class="comment">'+'<strong>'+data['username']+'</strong>'+'(刚刚)'+' <span style="color:red">回复</span> '
							+'<strong>'+data['reply_to']+'</strong>'+'：'
							+'<div>'+data['text']+'<div>'+'<a href="javascript:reply('+data['pk']+');">回复</a>'+'</div>';
							$('#comment_list').prepend(comment_html);
							//清空编辑框的内容
							$('#id_text').val('');
						}
					}
				},
				error:function(xhr){
					console.log(xhr);
				}
			});
			return false;
		});
	</script>
{% endblock %}

blog/templates/blog_list.html
{% extends 'base.html' %}

{# 页面标题 #}
{% block title %}
我的网站
{% endblock %}

{% block nav_blog_active %}active{% endblock %}

{# 页面内容 #}
{% block content %}
	<link rel="stylesheet" href="/static/blog/blog_list.css">
	<div class="container">
		<div class="row">
			<div class="col-sm-8 col-lg-10">
				<div class="panel panel-default">
					<div class="panel-heading"><h4>{% block blog_list_title %}<strong>{{ author }}</strong>的个人博客列表（一共有{{page_of_blogs.paginator.count}}篇博客）{% endblock %}</h4></div>
					<div class="panel-body">
						{% for blog in page_of_blogs.object_list %}
						<div class="blog">
						<h3><a href="/blog/articles/{{blog.id}}">{{blog.title}}</a></h3>
						<p class="blog-info">
							<span class="glyphicon glyphicon-tag" aria-hidden="true">
								<a href="/blog/type/{{blog.blog_type.pk}}">{{blog.blog_type}}</a>
							</span>
							<span class="glyphicon glyphicon-user" aria-hidden="true">
								<a href="{% url 'blog_list' blog.author %}">{{blog.author}}</a>
							</span>
							<span class="glyphicon glyphicon-time" aria-hidden="true">
								{{blog.created_time|date:"Y-m-d"}}
							</span>
							&nbsp;&nbsp;<span>阅读({{blog.readnum_function}})</span>
						</p>
						<p>{{blog.content|striptags|truncatechars:20}}</p>
						</div>
						{% empty %}
						<div class="blog">
							<h3>暂无博客......</h3>
						</div>
						{% endfor %}
						<hr>
					</div>
					<nav aria-label="Page navigation"><!--分页器-->
					  <ul class="pagination">
						<li>
						{# 上一页 #}
						{%if page_of_blogs.has_previous %}
						  <a href="?page={{page_of_blogs.previous_page_number}}" aria-label="Previous">
							<span aria-hidden="true">&laquo;</span>
						  </a>
						{% else %}
						{% endif %}
						</li>
						{# 全部页码 #}
						{% for page_num in page_of_blogs.paginator.page_range %}
							{% if page_num == page_of_blogs.number %}
							<li class="active"><span>{{page_num}}</span></li>
							{% else %}
							<li><a href="?page={{page_num}}">{{page_num}}</a></li>
							{% endif %}
						{% endfor %}
						<li>
						{# 下一页 #}
						{%if page_of_blogs.has_next %}
						  <a href="?page={{page_of_blogs.next_page_number}}" aria-label="Next">
							<span aria-hidden="true">&raquo;</span>
						  </a>
						{% else %}
						{% endif %}
						</li>
					  </ul>
					</nav>
				</div>	
				
			</div>
			<div class="col-sm-4 col-lg-2">
				<div class="panel panel-default">
					<div class="panel-heading"><h4>博客分类</h4></div>
					<div class="panel-body">
						<ul class="blog-types">
						{% for blog_type in blog_types %}
						<li><a href="/blog/type/{{blog_type.pk}}">{{blog_type}}({{blog_type.blog_count}})</a></li>
						{% empty %}
						<li>暂无分类</li>
						{% endfor %}
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
	
{% endblock %}

blog/templates/blog_manage.html
{% extends 'base.html' %}

{# 页面标题 #}
{% block title %}
博客管理
{% endblock %}

{# 页面内容 #}
{% block content %}
<div class="col-sm-10 col-sm-offset-1">
	<div>
		<h2>选择博客来修改</h2>
		<a href="{% url 'blog_add' %}" class="btn btn-primary pull-right">增加博客</a>
	</div>
	<form method="post">
		{% csrf_token %}
		<div class="results">
			<table class="table table-striped">
			<thead>
			<tr>
				<th><div class="text">标题</div></th>
				<th><div class="text">博客类型</div></th>
				<th><div class="text">作者</div></th>
				<th><div class="text">阅读量</div></th>
				<th><div class="text">创作时间</div></th>
				<th><div class="text">上次修改时间</div></th>
			</tr>
			</thead>
			
			<tbody>
			{% for blog in my_blogs %}
			<tr>
				<th><a href="{% url 'blog_change' blog.id %}">{{blog.title}}</a></th>
				<td>{{blog.blog_type}}</td>
				<td>{{blog.author}}</td>
				<td>{{blog.readnum_function}}</td>
				<td>{{blog.created_time}}</td>
				<td>{{blog.last_update_time}}</td>
			</tr>
			{% empty %}
				<td>暂无信息</td>
				<td>暂无信息</td>
				<td>暂无信息</td>
				<td>暂无信息</td>
				<td>暂无信息</td>
				<td>暂无信息</td>
			{% endfor %}
			</tbody>
			</table>
		</div>
	</form>
	<p>{{count}}篇博客</p><br><br>
</div>
{% endblock %}

blog/templates/blog_type_add.html
{% extends 'base.html' %}

{# 页面标题 #}
{% block title %}
增加博客类型
{% endblock %}

{# 页面内容 #}
{% block content %}
<div class="container">
	<div class="row">
		<div class="col-xs-10 col-sm-8 col-xs-offset-1 col-sm-offset-2">
			<form action="" method="POST">
				{% csrf_token %}
				<div class="input-group">
					<label for="id_blog_type">博客类型</label>
					<input type="text" name="blog_type" required placeholder="请输入博客类型" maxlength="30" id="id_blog_type" class="form-control" />
				</div><br>
				<br>
				<input type="submit" value="保存" class="btn btn-primary pull-right">
			</form>
		</div>
	</div>
</div>
{% endblock %}

blog/templates/blog_type_change.html
{% extends 'base.html' %}

{# 页面标题 #}
{% block title %}
修改博客类型
{% endblock %}

{# 页面内容 #}
{% block content %}
<div class="container">
	<div class="row">
		<div class="col-xs-10 col-sm-8 col-xs-offset-1 col-sm-offset-2">
			<form action="" method="POST">
				{% csrf_token %}
				<div class="input-group">
					<label for="id_blog_type">博客类型</label>
					<input type="text" name="blog_type" value="{{blog_type.type_name}}" required placeholder="请输入博客类型" maxlength="30" id="id_blog_type" class="form-control" />
				</div><br>
				<br><a href="{% url 'blog_type_delete' blog_type.id %}" class="btn btn-danger pull-left">删除</a>
				<input type="submit" value="保存" class="btn btn-primary pull-right">
			</form>
		</div>
	</div>
</div>
{% endblock %}

blog/templates/blog_type_manage.html
{% extends 'base.html' %}

{# 页面标题 #}
{% block title %}
博客类型管理
{% endblock %}

{# 页面内容 #}
{% block content %}
<div class="col-sm-10 col-sm-offset-1">
	<div>
		<h2>选择博客类型来修改</h2>
		<a href="{% url 'blog_type_add' %}" class="btn btn-primary pull-right">增加博客类型</a>
	</div>
	<form method="post">
		{% csrf_token %}
		<div class="results">
			<table class="table table-striped">
			<thead>
			<tr>
				<th><div class="text">博客类型</div></th>
				<th><div class="text">博客数量</div></th>
				<th><div class="text">用户</div></th>
			</tr>
			</thead>
			
			<tbody>
			{% for blog_type in my_blog_types %}
			<tr>
				<th><a href="{% url 'blog_type_change' blog_type.id%}">{{blog_type.type_name}}</a></th>
				<td>{{blog_type.blog_count}}</td>
				<td>{{blog_type.author}}</td>
			</tr>
			{% empty %}
				<td>暂无信息</td>
				<td>暂无信息</td>
				<td>暂无信息</td>
			{% endfor %}
			</tbody>
			</table>
		</div>
	</form>
	<p>{{count}}个博客类型</p><br><br>
</div>
{% endblock %}

blog/templates/blogs_with_type.html
{% extends 'blog_list.html' %}

{# 页面标题 #}
{% block title %}
{{blog_type.type_name}}
{% endblock %}

{% block blog_list_title %}
<h4>分类：{{blog_type.type_name}}（一共有{{page_of_blogs.paginator.count}}篇博客）</h4>
<a href="/blog/{{blog_type.author}}">查看{{blog_type.author}}的全部博客</a>
{% endblock %}

{# 页面内容用 blog_list.html #}