BlogSite/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import home,search

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor',include('ckeditor_uploader.urls')),
    path('',home,name='home'),
    path('user/',include('userInfo.urls')),
    path('blog/',include('blog.urls')),
    path('comment/',include('comment.urls')),
    path('search/',search,name='search'),
]

urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from . import views

urlpatterns=[
    path('<username>',views.blog_list,name='blog_list'),
    path('articles/<int:blog_pk>',views.blog_detail,name='blog_detail'),
    path('type/<int:blog_type_pk>',views.blogs_with_type,name='blogs_with_type'),
    path('manage/',views.blog_manage,name='blog_manage'),
    path('add/',views.blog_add,name='blog_add'),
    path('change/<int:blog_pk>',views.blog_change,name='blog_change'),
    path('delete/<int:blog_pk>',views.blog_delete,name='blog_delete'),
    path('blog_type/manage/',views.blog_type_manage,name='blog_type_manage'),
    path('blog_type/add/',views.blog_type_add,name='blog_type_add'),
    path('blog_type/change/<int:blog_type_pk>',views.blog_type_change,name='blog_type_change'),
    path('blog_type/delete/<int:blog_type_pk>',views.blog_type_delete,name='blog_type_delete'),
]

userInfo/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('login/',views.login,name='login'),
    path('register/',views.register,name='register'),
    path('logout/',views.logout,name='logout'),
    path('forget/',views.forget,name='forget'),
    path('code/',views.ve_code,name='code'),
    path('change_password/',views.change_password,name='change_password'),
    path('change/',views.change,name='change'),
    path('change_info/',views.change_info,name='change_info'),
]

userInfo/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserInfo(models.Model):
    user=models.OneToOneField(User,on_delete=models.DO_NOTHING,verbose_name='用户')
    code=models.CharField(max_length=20,verbose_name='验证码')
    introduction=models.TextField(verbose_name='简介')
    
    class Meta:
        verbose_name='用户信息'
        verbose_name_plural=verbose_name

userInfo/forms.py
from django import forms
from django.contrib import auth
from django.contrib.auth.models import User

class LoginForm(forms.Form):
    username=forms.CharField(label='用户名',required=True,\
                            widget=forms.TextInput(attrs={'class':"form-control",'placeholder':'请输入用户名'}))#required默认为True
    password=forms.CharField(label='密码',\
                            widget=forms.PasswordInput(attrs={'class':"form-control",'placeholder':'请输入密码'}))
    
    def clean(self):
        username=self.cleaned_data['username']
        password=self.cleaned_data['password']
        user=auth.authenticate(username=username,password=password)
        if user is None:
            raise forms.ValidationError('用户名或密码不正确!!!')
        else:
            self.cleaned_data['user']=user
        return self.cleaned_data
        
        
class RegForm(forms.Form):
    username=forms.CharField(label='用户名',required=True,max_length=30,min_length=3,\
                            widget=forms.TextInput(attrs={'class':"form-control",'placeholder':'请输入3-30位用户名'}))
    email=forms.EmailField(label='邮箱',required=True,\
                            widget=forms.EmailInput(attrs={'class':"form-control",'placeholder':'请输入邮箱'}))
    password=forms.CharField(label='密码',min_length=6,\
                            widget=forms.PasswordInput(attrs={'class':"form-control",'placeholder':'请输入密码(至少6位)'}))
    password_again=forms.CharField(label='再次输入密码',min_length=6,\
                            widget=forms.PasswordInput(attrs={'class':"form-control",'placeholder':'请再次输入密码'}))
    
    def clean_username(self):
        username=self.cleaned_data['username']
        if User.objects.filter(username=username).count()>0:
            raise forms.ValidationError('用户名已存在')
        return username
        
    def clean_email(self):
        email=self.cleaned_data['email']
        if User.objects.filter(email=email).count()>0:
            raise forms.ValidationError('邮箱已存在')
        return email
        
    def clean_password_again(self):
        password=self.cleaned_data['password']
        password_again=self.cleaned_data['password_again']
        if password!=password_again:
            raise forms.ValidationError('两次输入的密码不一致')
        return password_again
        
class ChangeInfoForm(forms.Form):
    username=forms.CharField(label='用户名',required=True,max_length=30,min_length=3,\
                            widget=forms.TextInput(attrs={'class':"form-control",'placeholder':'请输入3-30位用户名'}))
    text=forms.CharField(label='简介',widget=forms.Textarea(attrs={'class':"form-control",'placeholder':'请介绍一下你自己','rows':4}))
    
    def clean_username(self):
        username=self.cleaned_data['username']
        if User.objects.filter(username=username).count()>0:
            raise forms.ValidationError('用户名已存在')
        return username

userInfo/views.py
from django.shortcuts import render,render_to_response,redirect
from django.contrib import auth
from .forms import *
from django.contrib.auth.models import User
from .emailAPI.send_code import code,send
from .models import UserInfo
    
def login(request):
    if request.method=='POST':
        login_form=LoginForm(request.POST)
        if login_form.is_valid():
            username=login_form.cleaned_data['username']
            password=login_form.cleaned_data['password']
            user=auth.authenticate(request,username=username,password=password)
            if user is not None:
                auth.login(request,user)
                return redirect(request.GET.get('from','/'))
            else:
                login_form.add_error(None,'用户名或密码不正确')
    else:
        login_form=LoginForm()
    context={}
    context['login_form']=login_form
    return render(request,'login.html',context)
    
def register(request):
    if request.method=='POST':
        reg_form=RegForm(request.POST)
        if reg_form.is_valid():
            username=reg_form.cleaned_data['username']
            email=reg_form.cleaned_data['email']
            password=reg_form.cleaned_data['password']
            #创建用户
            user=User.objects.create_user(username=username,email=email,password=password)
            user.save()
            #向扩展的用户列表中添加信息
            ve_code=code()
            introduction="这个人很懒，什么都没写"
            user_info=UserInfo(user=user,code=ve_code,introduction=introduction)
            user_info.save()
            #登录用户
            user=auth.authenticate(request,username=username,password=password)
            auth.login(request,user)
            return redirect(request.GET.get('from','/'))
    else:
        reg_form=RegForm()
    context={}
    context['reg_form']=reg_form
    return render(request,'register.html',context)
    
def logout(request):
    auth.logout(request)
    return redirect(request.GET.get('from','/'))
    
def forget(request):
    context={}
    return render(request,'forget.html',context)
    
def ve_code(request):
    my_email = '1084578612@qq.com'
    license_code = 'uretsbdogxlmjbja'
    dest_email = request.POST.get('email','')
    msg_subject = '验证码'
    msg_content = code()
    
    # 存入数据库
    try:
        user=User.objects.get(email=dest_email)# 如果找不到会报错
    except:
        context={}
        return render(request,'email_error.html',context)
    user_info=UserInfo.objects.get(user=user)
    user_info.code=msg_content
    user_info.save()
    print(user_info)
    
    # 发送验证码
    try:
        send(my_email,license_code,dest_email,msg_subject,msg_content)
    except:
        print('验证码发送失败了')
        
    context={}
    context['email']=dest_email
    return render(request,'ve_code.html',context)
    
def change_password(request):
    if request.method=='POST':
        dest_email = request.POST.get('email','')
        user=User.objects.get(email=dest_email)# 如果找不到会报错
        user_info=UserInfo.objects.get(user=user)
        if user_info.code==request.POST.get('code',''):# 验证码是否匹配           
            context={}
            context['email']=dest_email
            return render(request,'change_password.html',context)
        else:
            context={}
            return render(request,'code_error.html',context)
    user=User.objects.get(username=request.user.username)    # 在个人中心中修改密码
    context={}
    context['email']=user.email
    return render(request,'change_password.html',context)
            
# 还没验证前后密码是否输入一致            
def change(request):
    if request.method=='POST':
        email=request.POST.get('email','')
        password=request.POST.get('password','')
        user=User.objects.get(email=email)
        username=user.username# 获取用户名
        user.set_password(password)
        user.save()
        #登录用户
        user=auth.authenticate(request,username=username,password=password)
        auth.login(request,user)
        return redirect(request.GET.get('from','/'))
        
def change_info(request):
    if request.method=='POST':
        change_info_form=ChangeInfoForm(request.POST)
        if change_info_form.is_valid():
            username=change_info_form.cleaned_data['username']
            text=change_info_form.cleaned_data['text']
            # 开始修改数据库
            user=User.objects.get(username=request.user.username)
            user.username=username
            request.user.username=username # 修改request
            user.save()
            user_info=UserInfo.objects.get(user=user)
            user_info.introduction=text
            user_info.save()
            change_info_form=ChangeInfoForm(initial={'username':user.username,'text':user_info.introduction}) #设置表单value
    else:
        print(request.user.username)
        user=User.objects.get(username=request.user.username)
        user_info=UserInfo.objects.get(user=user)
        change_info_form=ChangeInfoForm(initial={'username':user.username,'text':user_info.introduction}) #设置表单value
    context={}
    context['change_info_form']=change_info_form
    return render(request,'change_info.html',context)
    
    

userInfo/templates/change_info.html
{% extends 'base.html' %}

{# 页面标题 #}
{% block title %}
个人中心
{% endblock %}

{# 页面内容 #}
{% block content %}
	<div class="container">
		<div class="row">
			<div class="col-sm-8 col-lg-8">
				<div class="panel panel-default">
					<div class="panel-heading"><h4>个人信息</h4></div>
					<div class="panel-body">
						<form action="" method="POST">
							{% csrf_token %}
							{# change_info_form #}
							{% for field in change_info_form %}
							<label for="{{field.id_for_label}}">{{field.label}}</label>
							{{field}}
							<p class="text-danger">{{field.errors.as_text}}</p>
							{% endfor %}
							<br>
							<input type="submit" value="修改" class="btn btn-danger pull-right">
						</form>
					</div>
				</div>	
				
			</div>
			<div class="col-sm-4 col-lg-4">
				<div class="panel panel-default">
					<div class="panel-heading"><h4>其他修改操作</h4></div>
					<div class="panel-body">
						<ul class="blog-types">
							<a href="{% url 'change_password' %}">修改密码</a>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
	
{% endblock %}

userInfo/templates/change_password.html
{% extends 'base.html' %}

{# 页面标题 #}
{% block title %}
修改密码
{% endblock %}

{% block nav_blog_active %}
active
{% endblock %}

{# 页面内容 #}
{% block content %}
	<div class="container">
		<div class="row">
			<div class="col-xs-10 col-sm-4 col-xs-offset-1 col-sm-offset-4">
				<div class="panel panel-default">
					<div class="panel-heading">
						 <h3 class="panel-title">修改密码</h3>
					</div>
					 <div class="panel-body">
						 <form action="{% url 'change' %}" method="POST">
							{% csrf_token %}
							<input type="hidden" name="email" value="{{ email }}" id="id_email" />
							
							<label for="id_password">密码</label>
							<input type="password" name="password" id="id_password" class="form-control" minlength="6" placeholder="请输入密码(至少6位)" required />
			
							<br>
							<input type="submit" value="提交" class="btn btn-primary pull-right">
						</form>
					 </div>
				</div>
			</div>
		</div>
	</div>
	<link rel="stylesheet" href="/static/home.css">
{% endblock %}

userInfo/templates/code_error.html
{% extends 'base.html' %}

{# 页面标题 #}
{% block title %}
我的网站|错误
{% endblock %}

{% block nav_home_active %}
active
{% endblock %}

{# 页面内容 #}
{% block content %}
	<h1 class="home-content">验证码输入错误啦</h1>
	<link rel="stylesheet" href="/static/home.css">
{% endblock %}

userInfo/templates/email_error.html
{% extends 'base.html' %}

{# 页面标题 #}
{% block title %}
我的网站|错误
{% endblock %}

{% block nav_home_active %}
active
{% endblock %}

{# 页面内容 #}
{% block content %}
	<h1 class="home-content">该邮箱未在此网站注册</h1>
	<link rel="stylesheet" href="/static/home.css">
{% endblock %}

userInfo/templates/forget.html
{% extends 'base.html' %}

{# 页面标题 #}
{% block title %}
忘记密码|登录
{% endblock %}

{% block nav_blog_active %}
active
{% endblock %}

{# 页面内容 #}
{% block content %}
	<div class="container">
		<div class="row">
			<div class="col-xs-10 col-sm-4 col-xs-offset-1 col-sm-offset-4">
				<div class="panel panel-default">
					<div class="panel-heading">
						 <h3 class="panel-title">忘记密码</h3>
					</div>
					 <div class="panel-body">
						 <form action="{% url 'code' %}" method="POST">
							{% csrf_token %}
							<label for="id_email">邮箱</label>
							<input type="email" name="email" id="id_email" class="form-control" required placeholder="请输入邮箱" />
							<br>
							<input type="submit" value="提交" class="btn btn-primary pull-right">
						</form>
					 </div>
				</div>
			</div>
		</div>
	</div>
	<link rel="stylesheet" href="/static/home.css">
{% endblock %}

userInfo/templates/login.html
{% extends 'base.html' %}

{# 页面标题 #}
{% block title %}
我的网站|登录
{% endblock %}

{% block nav_blog_active %}
active
{% endblock %}

{# 页面内容 #}
{% block content %}
	<div class="container">
		<div class="row">
			<div class="col-xs-10 col-sm-4 col-xs-offset-1 col-sm-offset-4">
				<div class="panel panel-default">
					<div class="panel-heading">
						 <h3 class="panel-title">登录</h3>
					</div>
					 <div class="panel-body">
						 <form action="" method="POST">
							{% csrf_token %}
							{#login_form#}
							{% for field in login_form %}
							<label for="{{field.id_for_label}}">{{field.label}}</label>
							{{field}}
							<!--p class="text-danger">{{field.erros.as_text}}</p-->
							{% endfor %}
							<br>
							<span class="pull-left text-danger">{{login_form.non_field_errors}}</span>
							<span><a href="{% url 'forget' %}" class="pull-right text-primary">忘记密码</a></span><br><br>
							<input type="submit" value="登录" class="btn btn-primary pull-right">
						</form>
					 </div>
				</div>
			</div>
		</div>
	</div>
	<link rel="stylesheet" href="/static/home.css">
{% endblock %}

userInfo/templates/register.html
{% extends 'base.html' %}

{# 页面标题 #}
{% block title %}
我的网站|注册
{% endblock %}

{% block nav_blog_active %}
active
{% endblock %}

{# 页面内容 #}
{% block content %}
	<div class="container">
		<div class="row">
			<div class="col-xs-10 col-sm-4 col-xs-offset-1 col-sm-offset-4">
				<div class="panel panel-default">
					<div class="panel-heading">
						 <h3 class="panel-title">注册</h3>
					</div>
					 <div class="panel-body">
						 <form action="" method="POST">
							{% csrf_token %}
							{# reg_form #}
							{% for field in reg_form %}
							<label for="{{field.id_for_label}}">{{field.label}}</label>
							{{field}}
							<p class="text-danger">{{field.errors.as_text}}</p>
							{% endfor %}
							<br>
							<!--span class="pull-left text-danger">{{reg_form.non_field_errors}}</span-->
							<input type="submit" value="注册" class="btn btn-danger pull-right">
						</form>
					 </div>
				</div>
			</div>
		</div>
	</div>
	<link rel="stylesheet" href="/static/home.css">
{% endblock %}

userInfo/templates/ve_code.html
{% extends 'base.html' %}

{# 页面标题 #}
{% block title %}
输入验证码|登录
{% endblock %}

{% block nav_blog_active %}
active
{% endblock %}

{# 页面内容 #}
{% block content %}
	<div class="container">
		<div class="row">
			<div class="col-xs-10 col-sm-4 col-xs-offset-1 col-sm-offset-4">
				<div class="panel panel-default">
					<div class="panel-heading">
						 <h3 class="panel-title">输入验证码</h3>
					</div>
					 <div class="panel-body">
						 <form action="{% url 'change_password' %}" method="POST">
							{% csrf_token %}
							<input type="hidden" name="email" value="{{ email }}" id="id_email" />
							<label for="id_code">验证码</label>
							<input type="text" name="code" class="form-control" id="id_code" required maxlength="30" minlength="3" placeholder="请输入验证码" />
							<br>
							<input type="submit" value="提交" class="btn btn-primary pull-right">
						</form>
					 </div>
				</div>
			</div>
		</div>
	</div>
	<link rel="stylesheet" href="/static/home.css">
{% endblock %}